[project]
name = "hexlet-code"
version = "0.1.0"
description = "Some task manager"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=6.0",
    "dotenv>=0.9.9",
    "ruff>=0.14.10",
]
