databases:
  - name: task-manager-db
    plan: free

services:
  - type: web
    name: task-manager
    runtime: python
    plan: free
    buildCommand: './build.sh'
    startCommand: >
      python -m gunicorn task_manager.asgi:application
      -k uvicorn.workers.UvicornWorker
    envVars:
      - key: DATABASE_URL
        value: postgresql://python_project_52_db_cdoy_user:nvf2tYDthzjXLd6ZiJNjyh5avqKpdtqt@dpg-d538gaogjchc73f12irg-a/python_project_52_db_cdoy
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
