databases:
  - name: task-manager-db
    plan: free

services:
  - type: web
    name: task-manager
    runtime: python
    plan: free
    buildCommand: './build.sh'
    startCommand: >
      python -m gunicorn task_manager.asgi:application
      -k uvicorn.workers.UvicornWorker
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: task-manager-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
