name: Build
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Чекаут репозитория
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # лучше для SonarCloud

      # 2️⃣ Установка Python
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # 3️⃣ Установка uv
      - name: Install UV
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Add UV to PATH
        run: echo "$HOME/.uv/bin" >> $GITHUB_PATH

      # 4️⃣ Запуск тестов через uv с coverage
      - name: Run tests via UV
        run: uv run python -m pytest \
            task_manager/labels/tests.py \
            task_manager/statuses/tests.py \
            task_manager/tasks/tests.py \
            task_manager/users/tests.py \
            --cov=task_manager --cov-report=xml
        env:
          DJANGO_SETTINGS_MODULE: task_manager.settings

      # 5️⃣ Запуск SonarCloud анализа
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
