name: Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install uv
        run: pip install uv

      - name: Build project
        run: make build
        env:
          SECRET_KEY: "test-secret-key"
          DEBUG: "False"

      - name: Install dependencies (CI)
        run: make install_ci

      - name: Run tests with coverage
        run: make sq_test
        env:
          DJANGO_SETTINGS_MODULE: task_manager.settings
          SECRET_KEY: "test-secret-key"
          DEBUG: "True"

      - name: Check coverage file
        run: ls -lh coverage.xml

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_SCANNER_OPTS: >
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.python.version=3.12

      - name: SonarCloud Quality Gate
        uses: SonarSource/sonarqube-quality-gate-action@v1
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: SonarQubeScan
        uses: sonarsource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
        with:
          args: >
            -Dsonar.projectKey=BuilovAlmaty_python-project-52
            -Dsonar.organization=builovalmaty
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.projectName=python-project-52
            -Dsonar.sources=task_manager
            -Dsonar.exclusions=**/migrations/**,**/tests/**

